Revert "Move Obsidian cache workarounds to module"
This reverts commit 2ea3e7b3a9d466ef22452db97b76a89260f540fe.

The change caused an unexpected error:
```
error: Module `/nix/store/kx0bfk6z17xflziaz5dfb4kiqf8q10bd-source/util/obsidian.nix' has an unsupported attribute `boot'. This is caused by introducing a top-level `config' or `options' attribute. Add configuration attributes immediately on the top level instead, or move all of them (namely: boot networking services users) into the explicit `config' attribute.
```